#!/bin/sh

killall ModemManager
echo "killed ModemManager" 

echo "trying udhcpc" 
udhcpc -i wwan0

interface=$(ip a|grep wwan)

# The wwan0 interface will display "UNKNOWN" instead of "DOWN" if it is up
if [[ $interface == *"UNKNOWN"* ]]; then
	:

else
		
	killall ModemManager

	echo "setting operating mode online"
	qmicli -d /dev/cdc-wdm0 --dms-set-operating-mode='online'


	ip link set wwan0 down
	echo "wwan0 down"

	echo 'Y' | sudo tee /sys/class/net/wwan0/qmi/raw_ip
	ip link set wwan0 up
	echo "wwan0 up"

	echo "wds starting network"

# Update apn if necessary
	qmicli -p -d /dev/cdc-wdm0 --device-open-net='net-raw-ip|net-no-qos-header' --wds-start-network="apn='internet',ip-type=4" --client-no-release-cid

	udhcpc -i wwan0

fi
